import os
import sys
import argparse
from openai import OpenAI
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# --- 1. SETUP: Get API Key and Initialize Client ---
api_key = os.getenv("OPENAI_API_KEY")
if not api_key:
    sys.exit("Error: OPENAI_API_KEY not found. Please set it in a .env file.")

client = OpenAI(api_key=api_key)

# --- 2. HELPER FUNCTIONS ---

def read_file_content(filepath):
    """Reads the content of a file and returns it as a string."""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            return f.read()
    except FileNotFoundError:
        print(f"Error: File not found at {filepath}")
        sys.exit(1)
    except Exception as e:
        print(f"Error reading file {filepath}: {e}")
        sys.exit(1)

def get_completion(prompt, model="gpt-4-turbo-preview"):
    """Gets a completion from the OpenAI API."""
    try:
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": "You are a world-class cybersecurity expert and threat modeling assistant."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.2, # Lower temperature for more deterministic, factual output
        )
        return response.choices[0].message.content
    except Exception as e:
        print(f"Error calling OpenAI API: {e}")
        sys.exit(1)

def write_report(content, filename="THREAT_MODEL_REPORT.md"):
    """Writes the final report to a markdown file."""
    try:
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Successfully generated threat model report: {filename}")
    except Exception as e:
        print(f"Error writing report to {filename}: {e}")
        sys.exit(1)

# --- 3. PROMPT PREPARATION ---

def create_analysis_prompt(prompt_template_path, architecture_doc):
    """Creates a complete prompt by combining a template and the architecture document."""
    prompt_template = read_file_content(prompt_template_path)
    return prompt_template.format(architecture_document=architecture_doc)

# --- 4. MAIN EXECUTION LOGIC ---

def main():
    """Main function to orchestrate the threat modeling process."""
    parser = argparse.ArgumentParser(description="GPT Threat Modeling Bot")
    parser.add_argument("architecture_file", help="Path to the markdown file describing the system architecture.")
    args = parser.parse_args()

    print("--- Starting GPT Threat Modeling Bot ---")

    # Step 1: Read the architecture document
    print(f"Reading architecture file: {args.architecture_file}...")
    architecture_document = read_file_content(args.architecture_file)

    # Step 2: Perform STRIDE Analysis
    print("Performing STRIDE analysis...")
    stride_prompt = create_analysis_prompt("prompts/stride_prompt.md", architecture_document)
    stride_analysis = get_completion(stride_prompt)
    print("STRIDE analysis complete.")

    # Step 3: Perform OWASP Top 10 Analysis
    print("Performing OWASP Top 10 analysis...")
    owasp_prompt = create_analysis_prompt("prompts/owasp_prompt.md", architecture_document)
    owasp_analysis = get_completion(owasp_prompt)
    print("OWASP Top 10 analysis complete.")

    # Step 4: Combine analyses into a final report
    print("Assembling final report...")
    final_report = f"""# Threat Model Report

## System Architecture Overview

{architecture_document}

---

## 1. STRIDE Threat Analysis

{stride_analysis}

---

## 2. OWASP Top 10 Web Application Risk Analysis

{owasp_analysis}

---

*Disclaimer: This report was generated by an AI assistant. It should be used as a starting point for a comprehensive security review and not as a substitute for expert human analysis.*
"""

    # Step 5: Write the report to a file
    write_report(final_report)
    print("--- Process Complete ---")

if __name__ == "__main__":
    main()